sudo: required

language: python

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install linux-libc-dev libc6-dev
    - sudo apt-get install oracle-java8-installer
    - sudo useradd krun
    - sudo adduser krun sudo
    - sudo passwd -d krun

install:
    - pip install -r requirements.txt

script:
    - py.test --cov-report term --cov=krun  krun
    - uname -a
    - make --version
    - ldd --version
    - JAVA_CPPFLAGS='"-I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux"' JAVA_LDFLAGS=-L${JAVA_HOME}/lib ENABLE_JAVA=1 make
    - cd examples/benchmarks
    - make
    - make java-bench
    - cd ../
    - python ../krun.py --develop travis.krun
